# Generated by Django 2.2.14 on 2020-08-03 20:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('client_id_key', models.CharField(blank=True, max_length=256, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAPIRequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=256)),
                ('json_results', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('computed_median', models.FloatField(blank=True, null=True)),
                ('computed_min_temperature', models.FloatField(blank=True, null=True)),
                ('computed_max_temperature', models.FloatField(blank=True, null=True)),
                ('computed_min_humidity', models.FloatField(blank=True, null=True)),
                ('computed_max_humidity', models.FloatField(blank=True, null=True)),
                ('computed_average_humidity', models.FloatField(blank=True, null=True)),
                ('computed_average_temperature', models.FloatField(blank=True, null=True)),
                ('computed_median_humidity', models.FloatField(blank=True, null=True)),
                ('computed_median_temperature', models.FloatField(blank=True, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weatherapi.WeatherAPI')),
            ],
        ),
    ]
