# Generated by Django 2.2.14 on 2020-08-03 20:08
import uuid


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('client_id_key', models.CharField(blank=True, max_length=256, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('application_id', models.CharField(blank=True, max_length=256, null=True)),
                ('requires_oauth', models.BooleanField(default=False))
            ],
        ),
        migrations.CreateModel(
            name='WeatherAPIRequestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=False, null=False)),
                ('start_date', models.DateField(blank=False, null=False)),
                ('api_city', models.CharField(max_length=256)),
                ('user_city', models.CharField(max_length=256)),
                ('json_results', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
                ('computed_min_temperature', models.FloatField(blank=True, null=True)),
                ('computed_max_temperature', models.FloatField(blank=True, null=True)),
                ('computed_min_humidity', models.FloatField(blank=True, null=True)),
                ('computed_max_humidity', models.FloatField(blank=True, null=True)),
                ('computed_mean_humidity', models.FloatField(blank=True, null=True)),
                ('computed_mean_temperature', models.FloatField(blank=True, null=True)),
                ('computed_median_humidity', models.FloatField(blank=True, null=True)),
                ('computed_median_temperature', models.FloatField(blank=True, null=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='weatherapi.WeatherAPI')),
                ('created_date', models.DateTimeField(auto_now_add=True))
            ],
        ),
    ]
